# Generated by Django 5.2.7 on 2025-10-25 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('population', models.BigIntegerField()),
                ('currency_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('estimated_gdp', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('last_refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
                'ordering': ['name'],
            },
        ),
    ]
