from django.db import models
from django.utils import timezone

class Country(models.Model):
    """
    Represents a country with its currency and economic data.
    
    This model stores cached data from external APIs.
    """
    # Primary key (auto-generated by Django)
    id = models.AutoField(primary_key=True)
    
    # Required fields
    name = models.CharField(
        max_length=255, 
        unique=True,  # Ensures no duplicate country names
        db_index=True  # Speeds up lookups by name
    )
    population = models.BigIntegerField()  # Can be large numbers
    currency_code = models.CharField(
        max_length=10, 
        null=True,  # Can be null if country has no currency
        blank=True,
        db_index=True  # For filtering by currency
    )
    
    # Optional fields
    capital = models.CharField(max_length=255, null=True, blank=True)
    region = models.CharField(
        max_length=100, 
        null=True, 
        blank=True,
        db_index=True  # For filtering by region
    )
    flag_url = models.URLField(null=True, blank=True)
    
    # Computed/fetched fields
    exchange_rate = models.DecimalField(
        max_digits=20,  # Total digits
        decimal_places=6,  # Precision for exchange rates
        null=True,
        blank=True
    )
    estimated_gdp = models.DecimalField(
        max_digits=30,  # Very large numbers possible
        decimal_places=2,
        null=True,
        blank=True
    )
    
    # Timestamp
    last_refreshed_at = models.DateTimeField(default=timezone.now)
    
    class Meta:
        db_table = 'countries'  # Explicit table name
        ordering = ['name']  # Default ordering
        verbose_name_plural = 'Countries'  # For Django admin
    
    def __str__(self):
        """String representation of the model"""
        return self.name